In [ ]:
# Keras, Pytorch, TensorFlow

#Keras: 파이썬으로 구현된 간결한 딥러닝 문법관련 라이브러리 -> 굉장히 간결한 문법체계// 단점: 고도화된 딥러닝 문법 구현 불가
#Theano : 케라스보다는 업그레이드 된 라이브러리 모듈 
# TensorFlow :  Theano 확장판 -> 겁나 어려움
# Pytorch : 메타가 만든 파이썬 기반 딥러닝 라이브러리 모듈   ==> 대세

In [1]:
#Pytorch 설치
pip install torch torchvision torchaudio

Defaulting to user installation because normal site-packages is not writeable
   ---------------------------------------- 0.0/122.1 MB ? eta -:--:--
   --- ------------------------------------ 10.7/122.1 MB 59.2 MB/s eta 0:00:02
   ---- ----------------------------------- 12.8/122.1 MB 34.4 MB/s eta 0:00:04
   ---- ----------------------------------- 14.4/122.1 MB 24.5 MB/s eta 0:00:05
   ---- ----------------------------------- 14.7/122.1 MB 20.0 MB/s eta 0:00:06
   ----- ---------------------------------- 16.3/122.1 MB 16.2 MB/s eta 0:00:07
   ------ --------------------------------- 21.2/122.1 MB 17.7 MB/s eta 0:00:06
   -------- ------------------------------- 25.2/122.1 MB 18.1 MB/s eta 0:00:06
   -------- ------------------------------- 26.0/122.1 MB 16.0 MB/s eta 0:00:07
   ---------- ----------------------------- 30.7/122.1 MB 16.8 MB/s eta 0:00:06
   ---------- ----------------------------- 32.8/122.1 MB 16.3 MB/s eta 0:00:06
   ----------- ---------------------------- 36.4/12

  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.


In [3]:
import torch

print(torch.__version__)

2.13.0+cpu


In [4]:
x= torch.rand(5,3)

In [5]:
x

tensor([[0.8267, 0.2224, 0.0379],
        [0.1265, 0.8679, 0.9927],
        [0.7945, 0.6074, 0.2395],
        [0.8347, 0.3675, 0.3309],
        [0.9377, 0.5262, 0.5457]])

In [6]:
#고차연산식을 사용!

In [ ]:
#Deep learning >  Pytorch // numpy
#Machine learning >  Pandas

In [9]:
import numpy as np

data1 = np.array(10)
print(data1, data1.ndim, data1.shape) # scalar 0차원 tensor 

10 0 ()


In [10]:
import torch

data1 = torch.FloatTensor([1, 2])
print(data1,data1.dim(), data1.shape)  #vector 1차원 tensor

tensor([1., 2.]) 1 torch.Size([2])


In [ ]:
torch.zeros(a,b) #모든 원소를 0으로 초기화
torch.ones(a,b) # 모든 원소를 1로 초기화
torch.rand(a, b) #내부 원소들의 값을 0~1사이의 균등분포 방식의 난수를 생성
torch.randn(a, b) #내부 원소들의 값을 평균이 0이고, 표준편차가 1인 정규분포형태의 난수를 생성
torch.full((a, b), c) #내부 원소들의 tensor설정 및 값 초기화
torch.zeros_like() #이미 생성된 tensor와 같은 shape로 0이라는 값을 채우고자 할때

In [11]:
torch.zeros(2, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [12]:
torch.ones(2, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [13]:
torch.rand(2, 3)

tensor([[0.3410, 0.8551, 0.6753],
        [0.2019, 0.1183, 0.1393]])

In [14]:
torch.randn(2, 3)

tensor([[ 0.7592, -0.6176,  0.0140],
        [ 0.3925, -1.7410, -0.8582]])

In [ ]:
torch.full((2, 3), 5)