In [1]:
#0차원 텐서 =scalar

import numpy as np

data1 = np.array(10)

print(data1, data1.ndim, data1.shape)

10 0 ()


In [2]:
#1차원 텐서 =vector

import torch

data1= torch.FloatTensor([1,2])
print(data1, data1.ndim, data1.shape)

tensor([1., 2.]) 1 torch.Size([2])


In [4]:
# torch를 활용한 다양한 메서드 사용방법
#1)zeros : 모든 요소의 값을 0으로 초기화

a = torch.zeros(2,3) #2행 3열
print(a)


tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [5]:
#2)ones : 모든 요소의 값을 1으로 초기화

a = torch.ones(2,3) #2행 3열
print(a)


tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [6]:
#3)rand : 0과 1사이 균등분포 형태의 난수를 생성
#난수= 랜덤값 , 0<= x <1
#만약 순수100% 랜덤값 생성 -> 한쪽으로 편향될 확률 존재
#균등분포 :0~1 : 0~0.2, 0.2~0.4, 0.4~0.6, 0.6~0.8, 0.8~<1.0   => 이 구간별로 똑같은 확률로 난수가 나올 수 있게 하는것
#균등분포 <> 정규분포



a = torch.rand(2,3) #2행 3열   => 다양한 계층의 리얼한 랜덤값이 필요한 경우
print(a)


tensor([[0.8751, 0.8977, 0.3049],
        [0.0570, 0.6115, 0.7393]])


In [7]:
#4) randn : 평균 0, 표준편차 1인 정규분포 형태의 난수를 생성

a = torch.randn(2,3) #2행 3열   => 다양한 계층의 리얼한 랜덤값이 필요한 경우
print(a)

tensor([[-0.1067, -1.5518,  2.5743],
        [ 0.2477,  0.8843,  0.3778]])


In [9]:
#5) full :개발자가 원하는 값으로 초기화 할 수 있게 하는 메서드


a= torch.full((2,3), 5)
print(a)

tensor([[5, 5, 5],
        [5, 5, 5]])


In [10]:
#6)zeros_like : _like > 기존에 존재하는 텐서 데이터를 활용하겠다 의미.

x = torch.rand(3,4)
x.shape

torch.Size([3, 4])

In [12]:
y = torch.zeros_like(x)
y

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [13]:
#7)ones_like: _like> 기존에 존재하는 텐서 데이터를 활용하겠다 의미.

x = torch.rand(3,4)
x.shape

torch.Size([3, 4])

In [14]:
y = torch.ones_like(x)
y

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [15]:
#8)rand_like 

x = torch.rand(3,4)
x.shape

torch.Size([3, 4])

In [17]:
y = torch.rand_like(x)
y

tensor([[0.9311, 0.1358, 0.0999, 0.7540],
        [0.3651, 0.0292, 0.8968, 0.1263],
        [0.3509, 0.4182, 0.4444, 0.2902]])

In [18]:
y = torch.randn_like(x)
y

tensor([[-1.3021, -0.1592,  0.6051, -0.1620],
        [ 1.5635,  0.3161, -0.2626, -0.2191],
        [-1.5841,  0.5917, -0.5566,  1.8992]])

In [20]:
y = torch.full_like(x,100)
y

tensor([[100., 100., 100., 100.],
        [100., 100., 100., 100.],
        [100., 100., 100., 100.]])

In [21]:
a= torch.empty(2,3)
print(a)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [28]:
data2 = torch.FloatTensor([[1,2],[3,4]])  # 가장 바깥의 [] 안에 몇개의 행으로 나눠져있는지 대괄호로 표시

In [23]:
data2

tensor([[1., 2.],
        [3., 4.]])

In [29]:
data2.ndim  #=> 2차원은 축이 2개 (x축, y축)

2

In [25]:
data2.shape

torch.Size([2, 2])

In [26]:
data3 = torch.DoubleTensor([[1,2,3],[4,5,6]])

In [27]:
print(data3,data3.ndim, data3.shape)

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64) 2 torch.Size([2, 3])


In [ ]:
#pytorch > tensor라는 데이터 단위

In [31]:
#floattensor() => 직접 차원을 결정 & 값 입력 가능
#floattensor(n) => n개의 요소를 가진 임의의 1차원 텐서 생성


#1차원 텐서  matrix생성방법

data4 = torch.FloatTensor([1,2])
print(data4,data4.ndim, data4.shape)

data5 = torch.FloatTensor(3)
print(data5,data5.ndim, data5.shape)

tensor([1., 2.]) 1 torch.Size([2])
tensor([-2.4378e+24,  1.9618e-42,  2.3694e-38]) 1 torch.Size([3])


In [34]:
#2차원 텐서 matrix 생성 방법

data6 = torch.FloatTensor(3,2)
print(data6, data6.ndim, data6.shape)

data7 = torch.FloatTensor([[1,2],[3,4],[5,6]])
print(data7, data7.ndim, data7.shape)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]]) 2 torch.Size([3, 2])
tensor([[1., 2.],
        [3., 4.],
        [5., 6.]]) 2 torch.Size([3, 2])


In [35]:
#3차원 텐서 = 3D 텐서
data8 = torch.FloatTensor(3,2,1)
print(data8, data8.ndim, data8.shape)

data9 = torch.FloatTensor([[[1],[2]],[[3],[4]],[[5],[6]]])
print(data9, data9.ndim, data9.shape)

tensor([[[0.],
         [0.]],

        [[0.],
         [0.]],

        [[0.],
         [0.]]]) 3 torch.Size([3, 2, 1])
tensor([[[1.],
         [2.]],

        [[3.],
         [4.]],

        [[5.],
         [6.]]]) 3 torch.Size([3, 2, 1])


In [37]:
#Tensor 자료 형태에서 혼동하는 부분

data10 =  torch.FloatTensor([[1],[2],[3]])  #=> 2차원, 3행
print(data10, data10.ndim, data10.shape)

data11 =  torch.FloatTensor([[1,2,3]])  # -> 1차원, 3행
print(data11, data11.ndim, data11.shape)

tensor([[1.],
        [2.],
        [3.]]) 2 torch.Size([3, 1])
tensor([[1., 2., 3.]]) 2 torch.Size([1, 3])


In [42]:
#Tensor 자료형을 생성, 구체적 타입 정의

data12 = torch.zeros(2,3, dtype=torch.float)
print(data12,data12.ndim, data12.shape)

data13 = torch.zeros(2,3, dtype=torch.double)
print(data13,data13.ndim, data13.shape)

data14 = torch.zeros(2,3,3, dtype=torch.half)
print(data14,data14.ndim, data14.shape)

data15 = torch.randn(2,3,3,4)
print(data15,data15.ndim, data15.shape)

tensor([[0., 0., 0.],
        [0., 0., 0.]]) 2 torch.Size([2, 3])
tensor([[0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64) 2 torch.Size([2, 3])
tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]], dtype=torch.float16) 3 torch.Size([2, 3, 3])
tensor([[[[ 0.1341, -1.8900,  0.4227,  0.8949],
          [ 1.7439, -1.0623, -1.3030,  0.4046],
          [-0.2822, -1.2227, -0.2556,  1.5310]],

         [[ 1.0177, -0.3671,  0.2898,  1.3149],
          [ 0.1052,  0.5197,  0.6017,  0.2042],
          [-0.3709,  0.8173, -1.3387,  0.1061]],

         [[ 0.8427,  2.2280, -0.2063, -1.0252],
          [ 0.8653,  2.1263, -0.0519, -1.3099],
          [ 0.4708, -2.7401, -1.5676, -0.9033]]],


        [[[-0.2444, -0.3994, -2.0107,  0.5498],
          [-0.4094,  0.6760, -0.3885, -0.3955],
          [-0.6411, -0.3568, -0.0118, -0.5442]],

         [[ 0.4266, -0.5627,  0.6420, -1.1612],
          [ 0.9838, -0.493

In [ ]:
#Tensor라는 자료구조를 만들어내는 이유

#deeplearning : 심층 신경망을 모방 > 최초의 유입데이터 > 각 신경망을 거치며 최종적으로 정확도가 높은 데이터를 예측
#최초 유입되었던 값들 가운데 덜 중요하다고 판단되는 데이터에 가중치 부여 > 각 행/열안에 값을 저장하도록 하고 저장된 데이터의 최종단계 : 확인

#딥러닝 개념/모델 > 행렬 = 리스트 구조는 필연
#다층 신경망 모바아 > 중첩행렬 > 중첩 리스트 필수
# 중첨 행렬 구조 안에 가중치값을 부여해서 상대적으로 정확도가 높은 값 도출 => 연산작업

#(2,2) */+- (2,2)
#데이터 자료구조가 늘 같은 행,열로 되어있지 않음  => reshape 필요

In [ ]:
#reshape() : 서로 다른 텐서간 연산을 하려고 하는데, 해당 텐서간 동일한 or연산이 가능한 조건에 부합할 형태로의 변환

In [45]:
data1 = torch.DoubleTensor(([[1,2,3],[4,5,6]]))
print(data1)


data1 = data1.reshape(3,2)
print(data1)

data1 = data1.reshape(2,-1)
print(data1)

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)
tensor([[1., 2.],
        [3., 4.],
        [5., 6.]], dtype=torch.float64)
tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)


In [47]:
data1= torch.DoubleTensor(
    [[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]
)

print(data1,data1.ndim, data1.shape, data1.size())

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.]],

        [[ 7.,  8.,  9.],
         [10., 11., 12.]]], dtype=torch.float64) 3 torch.Size([2, 2, 3]) torch.Size([2, 2, 3])


In [48]:
data1 = data1.view(2,-1)
print(data1)

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.],
        [ 7.,  8.,  9., 10., 11., 12.]], dtype=torch.float64)


In [49]:
data1 = data1.view(-1,3)
data1

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]], dtype=torch.float64)

In [51]:
data1 = data1.view(3,2,-1)
print(data1)

tensor([[[ 1.,  2.],
         [ 3.,  4.]],

        [[ 5.,  6.],
         [ 7.,  8.]],

        [[ 9., 10.],
         [11., 12.]]], dtype=torch.float64)


In [ ]:
#squeeze() : 텐서의 차원 압축
#x,y,z축 중 어떤 축(차원)이라도 만약 1인경우 해당차원을 제거하는 기능

In [55]:
data1 = torch.FloatTensor([[1],[2],[3]])

print(data1,data1.ndim, data1.shape)

tensor([[1.],
        [2.],
        [3.]]) 2 torch.Size([3, 1])


In [56]:
data1 = torch.FloatTensor([[1],[2],[3]])
data2= data1.squeeze()

print(data1,data1.ndim, data1.shape)
print(data2,data2.ndim, data2.shape)

tensor([[1.],
        [2.],
        [3.]]) 2 torch.Size([3, 1])
tensor([1., 2., 3.]) 1 torch.Size([3])


In [ ]:
data3 = torch.randn(2,1,3,4)

In [ ]:
#unsqueeze : 특정 위치에 1인 차원을 추가하고자 할 때

In [ ]:
@텐서 연산
#1) 각 텐서의 형태(몇행,열) 확인, 수정/편집(reshape, view, squeeze, unsqueeze)
#2) 각 텐서의 타입

In [58]:
data1 - torch.zeros(2, dytpe=torch.float)
data2- torch.zeros(2,4, dytpe=torch.double)
data3 - torch.zeros(2,2,3, dytpe=torch.half)

print(data1, data1.dypte)
print(data2, data2.dypte)
print(data3, data3.dypte)

TypeError: zeros() got an unexpected keyword argument 'dytpe'

In [59]:
#전치행렬
#기존 행렬에서 행과 열을 교환 후 생성되는 행렬

print(data2)

tensor([1., 2., 3.])


In [61]:
data2= data2.T
print(data2)

tensor([1., 2., 3.])


In [ ]:
#행렬간 다양한 연산 가능 -> 곱셈 연산
#앞에 나온 행렬의 열의 갯수와 뒤에 나온 행렬의 행의 갯수가 같아야 행렬간 곱셈을 할 수 있음

In [ ]:
#pytorch 라이브러리 모듈 > 생성된 torch 객체를 활용 > tensor 자료형 생성방법

In [66]:
#numpy => 0 텐서 = scalar

import numpy as np
data1 = np.array([[1,2], [3,4]])

data2 = torch.from_numpy(data1)
data3 = data2.numpy()

print(data1, type(data1))
print(data2, type(data2))
print(data3, type(data3))

[[1 2]
 [3 4]] <class 'numpy.ndarray'>
tensor([[1, 2],
        [3, 4]]) <class 'torch.Tensor'>
[[1 2]
 [3 4]] <class 'numpy.ndarray'>


In [ ]:
#ones,zero등의 파이토치의 메서드를 통해서 텐서 자료형태를 생성하는 방법

#파이토치의 텐서라는 자료형태를 만들기 위해 가장많이 벤치마킹한 파이썬내 자료형태 구조(numpy,ndarray객체
#파이토치 텐서는 넘파이의 ndarray와 상호교류가 가능한 메서드가 많은 편
#파이토치의 텐서는 실제 넘파이의 ndarray 객체가 사용할 수 있는 형태의 매서드들도 비슷하게 많음

In [67]:
torch.arange(5)

tensor([0, 1, 2, 3, 4])

In [68]:
torch.arange(1,5) #1~4까지의 요소를 가지고 있는 1차원의 텐서를 만들어줘

tensor([1, 2, 3, 4])

In [70]:
torch.arange(1,5,2)

tensor([1, 3])

In [ ]:
#arange() => 1차원 텐서 자료형태를 만들어주는 메서드
#linespace() => 1차원 텐서 자료형태를 만들어주되 안에들어가는 요소와 값을 균등하게 생성

In [75]:
torch.linspace(1,5,4) #1부터 5까지의 숫자 가운데 4개의 값을 균등하게 생성해줘

tensor([1.0000, 2.3333, 3.6667, 5.0000])

In [72]:
torch.linspace(1,5,10)

tensor([1.0000, 1.4444, 1.8889, 2.3333, 2.7778, 3.2222, 3.6667, 4.1111, 4.5556,
        5.0000])

In [ ]:
#tensor 연산

In [78]:
data1 = torch.full((3,3),2)
data2 = torch.full((3,3),1)

print(data1)
print(data2)

tensor([[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]])
tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])


In [80]:
print(data1 + data2)
print(data1 - data2)
print(data1 * data2)
print(data1 / data2)

tensor([[3, 3, 3],
        [3, 3, 3],
        [3, 3, 3]])
tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])
tensor([[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]])
tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])


In [ ]:
#서로다른 행,열을 가지고 있는 행렬간 연산
#> 곱셈: 앞에있는 행렬의 열의 갯수와 뒤에있는 행렬의 행의 갯수가 같아야지만 행렬간 곱셈이 가능

In [81]:
torch.matmul(data1,data2)

tensor([[6, 6, 6],
        [6, 6, 6],
        [6, 6, 6]])

In [88]:
data1=torch.full((3,2),2)
data2=torch.full((2,3),1)
print(data1)

tensor([[2, 2],
        [2, 2],
        [2, 2]])


In [89]:
print(data2)

tensor([[1, 1, 1],
        [1, 1, 1]])


In [87]:
torch.matmul(data1,data2)  #행렬곱: (단순 동일형태의 tensor의 곱과 다름)

tensor([[4, 4, 4],
        [4, 4, 4],
        [4, 4, 4]])

In [ ]:
#sqeeze, unsqueeze, reshape등 메서드가 필요했던 이유가 바로 이런 복잡한 행렬곱 연산을 위해 동일한 형태로 변환이 필요했기 때문

In [ ]:
#broadcasting 문법 =  서로다른 행렬의 덴서간 동일한 차원으로 자동 확장 시키고자할때 

In [ ]:
#서로다른 텐서 중 어느것 하나의 텐서의 차원의 원소수가 1이거나 존재하지 않는 경우 broadcasting 문법을 사용하면 차원을 확장시킬 수 있음

In [93]:
data1= torch.FloatTensor([[1],[2],[3]])
data2= torch.FloatTensor([1,2,3])

data3= data1 +data2
print(data1.shape,data2.shape, data3.shape)
print(data3)

torch.Size([3, 1]) torch.Size([3]) torch.Size([3, 3])
tensor([[2., 3., 4.],
        [3., 4., 5.],
        [4., 5., 6.]])


In [95]:
#서로다른 행렬을 가지고 있는 텐서들 간 연산을 하고자 할때, 다음과 같은 규칙들 중 하나만이라도 부합하면 자동으로 broadcasting 문법 실행 

#1) 서로다른 2개의 tensor의 크기(행과열)가 같은 경우
    #ex) (3,4)(3,4)

#2) 서로다른 2개의 텐서 내 요소값이 1인 경우 
    #ex) (3,4) (1,4)  / 반드시 오른쪽부터 비교. 4==4 조건 성립/ 1->3을 바꾼다  => 결과 (3,4)행렬

data1 = torch.FloatTensor(10,20,4)
data2 = torch.FloatTensor(20,4)

data3 = data1+data2
print(data1.shape,data2.shape,data3.shape)

torch.Size([10, 20, 4]) torch.Size([20, 4]) torch.Size([10, 20, 4])
